Feat/new gui implentation #20
MninaTB/AE_Quiz_Projekt24 pull request #59
Opened 2021-05-16 14:58 UTC by NiklasEsser

Erstmal nur eine funktionale StartGUI bisher.
GameGUI & ResultGUI coming soon!
(Hab EndGUI jetzt ResultGUI genannt, Anpassung in Dokumentation mach ich noch)

2021-05-17 11:11 UTC, MninaTB requested changes
Bezüglich der strukturellen Aufteilung wäre es denke ich sinnvoll ein generelles Entwurfsmuster zu nutzen. Das reduziert die Abhängigkeiten zwischen den einzelnen Screens die wir jetzt haben, es ermöglicht es bestimmte Views (damit sind die einzelnen Screenlayouts gemeint) - zum Beispiel zur Bearbeitung und Erstellung von Fragen - wiederzuverwedenen. 
Dabei würde auch die Logik wie die Views verwendet werden in einzelne Controller unterteilt werden. 

Da wir langsam in Zeitdruck geraten würde ich vorschlagen, wir starten wirklich nur mit dem Startscreen und das MVC - Layouts (wirst du in den Tutroials sehen). In den Links unten ist ein Tutorial und ein Github Repository in dem das jemand mit Java Swing angewandt hat. 

Versuche bitte bis morgen Abend nur den Startscreen und den Endscreen fertig zu bekommen und lass den anderen Kram erstmal weg, damit wir die Struktur schonmal rein bekommen. Danach müssen wir uns nun wirklich beeilen, weshalb wir die Screens dann zwischen uns aufteilen sollten. 

https://ssaurel.medium.com/learn-to-make-a-mvc-application-with-swing-and-java-8-3cd24cf7cb10

https://github.com/ashiishme/java-swing-mvc

P.S.: Aktuell kompilieren deine Änderungen auch nicht. Das siehst du an dem roten Kreuz hinter deinem PullRequest ;) Da könntest du nächstes Mal noch drauf gucken :)

2021-05-17 11:43 UTC, NiklasEsser commented on src/gui/MainGUI.java
> +	public static void main(String[] args) {
Das war nur damit ich die GUI starten kann und somit testen wie sie aussieht, natürlich kommt das noch weg.

2021-05-17 12:41 UTC, NiklasEsser commented
Also eigentlich würde ich sagen, dass ich eine generelles Entwurfsmuster nutze, was man so leider nur noch nicht ganz sieht. Es sollte klarer werden wenn ihr auch die anderen GUI-Klassen demnächst sehen werdet zu der bereits comitteten `StartGUI.java`. Die `MainGUI.java` soll als dieser songenannte Controller fungieren indem er alle graphischen Änderungen verwaltet und als leeres Fenster (Container) dient. Die anderen GUI-Klassen dienen nur dazu die Komponenten (Texte, Knöpfe und etc.) auf dieses leere Fenster zu schmeißen.
So hab ich das zumindenst angedacht und das da wo das Programm im Hintergrund abläuft, denke mal `Main.java`, einfach ein Objekt der `MainGUI.java` erstellt wird und daran dann Methoden aufgerufen werden für optische Änderungen.
Als Beispiel, eine Frage soll geladen werde in der GameGUI, da überleg ich erstmal welche Daten brauch ich dann vom dem Spiel für die GUI und was ändert sich optisch alles so. Ergebnis wäre in etwa solch eine Methode:
```
public void loadQuestion(String question, String a1, String a2, String a3, String a4, String category) {
    questionLabel.setText(question);
    answer1Label.setText(a1);
    answer2Label.setText(a2);
    answer3Label.setText(a3);
    answer4Label.setText(a4);
    categoryLabel.setText(category);
    levelCounter++;
    gui.repaint()
}
```

P.S. Wegen der Komplimierung, da wurde mir ein 'ß' in einem Kommentar als Fehler gezeigt, dass hab ich dann zu 'ss' geändert.

2021-05-17 13:16 UTC, MninaTB commented
Wenn die MainGUI.java als gesammelter Controller fungiert, ist doch die ganze Logik des Frontends in einer Klasse. Das führt dazu, dass wir keine wirkliche Trennung haben zwischen den verschiedenen Screens. Das ist soweit ich das bisher beurteilen kann, kein allgemein bekanntes Enwturfsmuster - oder welchem sollte es entsprechen? :) 

In diesem Fall würde ich sagen, dass das Rad schon exisiter und wir nicht ganz so viel eigenen Gehirnschmalz brauchen :D

2021-05-17 14:27 UTC, NiklasEsser commented
Meinst du, dass wir das dann noch weiter Aufteilen sollen also eine weitere Ebene einfügen sollen z.B. die Klassen `MainStartGUI.java`, `MainGameGUI.java`, `MainOptionsGUI.java` und `MainResultGUI.java` jeweils als ein Controller für den jeweiligen Screen nutzen sollten und dann `MainGUI.java` als Controller von diesen Klassen dienen würde?


Aber wenn du meinst, du willst die Screens komplett voneinander trennen zu wollen ist das unmöglich, weil irgendwo müssen ja zusammenlaufen sonst kann man ja nicht zwischen den Screens wechseln.

2021-05-17 15:31 UTC, MninaTB commented
Du kannst dir gerne diesen Link nochmal angucken, da steht in der Antwort relativ exakt beschrieben was die einzelnen Komponenten machen sollen und wofür sie da sind :) Sonst kann ich dir auch ein Beispiel schreiben, wenn dir das helfen würde? :) 

https://stackoverflow.com/questions/5217611/the-mvc-pattern-and-swing -> hier der Antwortbereich ;)

2021-05-17 16:26 UTC, NiklasEsser commented
Ist es den so wichtig, dass wir irgendein bekanntes Entwurfsmuster für unser Projekt nutzen? Dann ist das, was ich meine mit einem Entwurfsmuster mein selbst erstelltes Entwurfsmuster scheinbar. Das bekannte Entwurfsmuster umzusetzen kostet, meines Erachtens, extra Zeit und Aufwand. Sollte man sowas nicht im Ermessen der Person lassen, die das programmiert, solange das sauber, übersichtlich, strukturiert und für die anderen nachvollziehbar programmiert ist?
Zum Beispiel ich kenn jetzt dieses Muster nicht wirklich und versteh das jetzt nicht auf Anhieb direkt. Ich müsste mir erstmal Zeit nehmen um mich damit auseinanderzusetzen damit ich das Prinzip davon verstehe und keine Ahnung wie lange das dauert. Dazu müsste ich dann auch noch den Code komplett umstrukturieren. Das könnte mich um 2-3 Tage zurückwerfen statt das ich so weiter wie ich kann, solang am Ende sauberer, übersichtlicher, strukturierter und für die anderen nachvollziehbarer Code raus kommt.
Ich mein das jetzt nicht böse, aber soweit ich das verstehe sind wir doch schon unter Zeitdruck oder nicht?
Ich werde jetzt erstmal noch die GameGUI so zu Ende machen. (ResultGUI ist fertig, commite ich heute noch, aber versuch noch vorher GameGUI fertig)

2021-05-17 17:48 UTC, MninaTB commented
Ja, ich verstehe deine Bedenken. 
Das Problem mit der Lösung im Moment wäre für mich die steigende Komplexität je mehr wie unser Spiel erweitern wollen - die komplette Logik wäre in einer Datei und das wäre sehr unübersichtlich und schwer zu warten. Wenn man einen Teilbereich anpassen will, läuft man Gefahr schnell die Übersicht zu verlieren.
Das Problem mit so langen PullRequests und auch mit dem späten pushen von allen Sachen auf einmal ist, dass das Team keine Zeit bekommt alles zu reviewen, sodass man damit weiter arbeiten kann. Außerdem wird das Review sehr komplex und man muss im schlimmsten Fall sehr viel wieder umstellen und Zeit geht verloren. 
Deswegen bin ich immer dafür das Tickets die so umfangreich und wichtig sind - darauf baut ja viel auf - zeitnah in kleinen Schritten gepushed werden, sodass man sie erstmal besprechen kann. Das fehlt im Moment bei dem Bearbeitungs-Screen auch. Das ist auch nicht böse gemeint und klar würde ich nicht alles anmerken, was ich selbst minimal anders gemacht hätte, wenn deine Lösung auch vollkommen in Ordnung ist. Hierbei geht es mir aber jetzt tatsächlich um den grundlegenden Aufbau der sonst wirklich sehr unübersichtlich werden könnte. 

Ich kann sehr gut verstehen, dass du denkst, dass das sehr umfangreich ist und man lange brauchen könnte um sich das Wissen anzueignen. Ich könnte dir ein Beispiel des StartScreens machen und du kannst anhand dessen die anderen Screens überarbeiten, wenn du möchtest? :) Dann sollte es eigentlich nicht mehr so komplex sein, denke ich :)

Ich fände es doof, wenn du das jetzt machst, weil du dich verpflichtet fühlst, deswegen hier eine Pro/Contra Liste und du kannst dich absolut selbst entscheiden. Ich werde danach einfach so weiter machen, wie du und das restliche Team es für sinnvoll erachten und mich dementsprechend anpassen :) 

Pro - für die Neustrukturierung
- Viele Anleitungen und Tutorials für MVC - sodass jeder aus dem Team sich theoretisch schnell einarbeiten könnte
- MVC ist etabliert und erprobt
- bietet bessere Übersichtlichkeit
- bietet leichtere Wartbarkeit
- leichter Erweiterbar
- Logik von Frontend und Backend ist leicht zu trennen 
- Einzelne Views lassen sich einfach wiederverwenden 
- Nach mittel- langer Zeit gute Strukturierung im Projekt möglich 

Contra - Neustrukturierung
- Zeit ist bereits investiert
- Funktionalität fast fertig (deiner Aussage nach :) )
- Du hast bereits einen Überblick und komplettes Verständnis für dein Werk :)

2021-05-17 21:28 UTC, NiklasEsser commented
So ich habe jetzt meine main()-Methode rausgeworfen und die MainGUI in die Main-Klasse gepackt. Der Komplimierungsfehler scheint auch weg zu sein mit dem 'ss' statt 'ß'.
Die ResultGUI kann man mometan testweise über die 'Einstellungen' öffnen und halt zurück mit 'Zur Startseite'. GameGUI braucht leider doch noch was.

Bezüglich des Beispiels für den StartScreen, wenn du das wirklich für mich machen würdest, würde ich das dann auch auf die anderen Screens übernehmen mit dem Beispiel als Referenz. Ich lasse die Entscheidung bei dir, weil du sogesehen die Projektleiterin unseres Teams bist (zu mindestens für mich) :smile:.

P. S. Mir wurde `var q = new QuestionParser();` als Fehler anzeigt und ich habe das korrigiert zu `QuestionParser q = new QuestionParser();`. Eigentlich wären da noch 7 `import ...;` die mir als ungenutzt anzeigt werden, aber da das kein Fehler ist hab ich das erstmal so belassen.

2021-05-18 08:15 UTC, NiklasEsser commented
Jetzt ist auch GameGUI drin. Schon einmal in voraus, ich bin damit optisch noch nicht ganz zufrieden, aber es ist nah dran.

2021-05-27 09:13 UTC, closed without merging